### ISSUE TITLE
SSEStream unpredictably throws unwanted IOException("Canceled")

### ISSUE THREAD

**Issue by lijamie98** [lightsail-network/java-stellar-sdk#649]
I encountered an unpredictable and unwanted exception thrown from the SSEStream of the Java Horizon SDK (https://github.com/lightsail-network/java-stellar-sdk). 

```
java.io.IOException: Canceled
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:72)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at org.stellar.sdk.requests.ClientIdentificationInterceptor.intercept(ClientIdentificationInterceptor.java:22)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
    at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    ...
```

**Here is the root cause:**

When `reconnectTimeout` expires, [restart](https://github.com/lightsail-network/java-stellar-sdk/blob/master/src/main/java/org/stellar/sdk/requests/SSEStream.java#L96) is called
eventSource.cancel() is triggered.

A new `StellarEventSourceListener` [is created for the new event source.](https://github.com/lightsail-network/java-stellar-sdk/blob/master/src/main/java/org/stellar/sdk/requests/SSEStream.java#L185)

The previously canceled `StellarEventSourceListener` (the one that we don't track) can receive the `IOException (Canceled)`  because the call was canceled in [okhttp](https://github.com/square/okhttp/blob/master/okhttp-sse/src/main/kotlin/okhttp3/sse/internal/RealEventSource.kt#L114). The origin of the exception is[ here.](https://github.com/square/okhttp/blob/master/okhttp-sse/src/main/kotlin/okhttp3/sse/internal/RealEventSource.kt#L84)

I suggest the `SSEStream` to not fire the `onFailure()` to the listener if the exception was targeting the canceled `StellarEventSourceListener`.

**Comment by lijamie98** [comment]
Thank you so much for the fast fix. :-)
